<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GHLearning.TPLDataflow.SharedKernel\GHLearning.TPLDataflow.SharedKernel.csproj" />
  </ItemGroup>

</Project>
